use_frameworks!

target 'Simple-KeychainSwift_Example' do
  pod 'Simple-KeychainSwift', :path => '../'
  platform :ios, '11.0'

  target 'Simple-KeychainSwift_Tests' do
    inherit! :search_paths

    
  end
end
